include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - require_trailing_commas
    - sort_pub_dependencies
    - unnecessary_null_checks